services:
  hima-ilkom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hima-ilkom-production
    restart: unless-stopped
    ports:
      - 8206:80
    env_file:
      - .env
    volumes:
      - ./.env:/var/www/html/.env
      - app-storage:/var/www/html/storage/app
      - app-logs:/var/www/html/storage/logs

volumes:
  app-storage:
    driver: local
  app-logs:
    driver: local